version: '3.8'

services:
  # PostgreSQLデータベース
  postgres:
    image: postgres:16-alpine
    container_name: thinking-blocks-db
    environment:
      POSTGRES_DB: thinking_blocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - thinking-blocks-network

  # Redisキャッシュ
  redis:
    image: redis:7-alpine
    container_name: thinking-blocks-redis
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - thinking-blocks-network

  # Goバックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: thinking-blocks-backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/thinking_blocks?sslmode=disable
      - REDIS_URL=redis:6379
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - ENVIRONMENT=production
      - GIN_MODE=release
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - thinking-blocks-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.jsフロントエンド
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinking-blocks-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - thinking-blocks-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Prometheus (メトリクス収集)
  prometheus:
    image: prom/prometheus:latest
    container_name: thinking-blocks-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - thinking-blocks-network

  # Grafana (可視化)
  grafana:
    image: grafana/grafana:latest
    container_name: thinking-blocks-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - thinking-blocks-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  thinking-blocks-network:
    driver: bridge
