name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  # バックエンドをRailwayにデプロイ
  deploy-backend:
    name: Deploy Backend to Railway
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: npm install -g @railway/cli
    
    - name: Deploy to Railway
      run: |
        cd backend
        railway up --service thinking-blocks-backend
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
    - name: Get Railway URL
      id: railway-url
      run: |
        cd backend
        URL=$(railway status --service thinking-blocks-backend | grep "URL:" | awk '{print $2}')
        echo "url=$URL" >> $GITHUB_OUTPUT
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
    - name: Health Check
      run: |
        sleep 30
        curl -f ${{ steps.railway-url.outputs.url }}/health || exit 1

  # フロントエンドをVercelにデプロイ
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: deploy-backend
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Vercel CLI
      run: npm install -g vercel
    
    - name: Pull Vercel Environment
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Build Project
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Deploy to Vercel
      id: deploy
      run: |
        URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
        echo "url=$URL" >> $GITHUB_OUTPUT
    
    - name: Health Check
      run: |
        sleep 20
        curl -f ${{ steps.deploy.outputs.url }} || exit 1
    
    - name: Comment Deployment URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Deployed to: ${{ steps.deploy.outputs.url }}'
          })

  # デプロイメントステータス確認
  verify-deployment:
    name: Verify Deployment
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    
    steps:
    - name: Check Backend Health
      run: |
        curl -f https://thinking-blocks-backend.railway.app/health || exit 1
    
    - name: Check Frontend
      run: |
        curl -f https://thinking-blocks.vercel.app || exit 1
    
    - name: Deployment Success
      run: |
        echo "✅ Deployment successful!"
        echo "Frontend: https://thinking-blocks.vercel.app"
        echo "Backend: https://thinking-blocks-backend.railway.app"
